### PR TITLE
always include requirements in the pack

### PR DESCRIPTION
**Pull request by ainquel**
Hi @facundobatista 

I've found that pyempaq can fail to unpack a pack when using `requirements` along with `include`
or `exclude` depending on the user's configuration.

Currently requirements are included thanks to the default include's configuration `./**`.
If users are not including them explicitly or if they are excluding them, requirements might not be in the pack leading to the unpacker crashing.

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/me/pyempaq/req.pyz/__main__.py", line 206, in <module>
  File "/home/me/pyempaq/req.pyz/__main__.py", line 191, in run
  File "/home/me/pyempaq/req.pyz/__main__.py", line 135, in setup_project_directory
  File "/home/.local/lib/python3.10/site-packages/pyempaq/common.py", line 49, in logged_exec
    raise ExecutionError(f"Command {cmd} ended with retcode {retcode}")
pyempaq.common.ExecutionError: Command ['/home//.local/share/pyempaq/req-20230619161451/project_venv/bin/pip3', 'install', '-r', '/home/.local/share/pyempaq/req-20230619161451/orig/requirements.txt'] ended with retcode 1
````

When executing manually this command, I've got
`ERROR: Could not open requirements file: [Errno 2] No such file or directory: '/home/.local/share/pyempaq/req-20230619161451/orig/requirements.txt`

example of problematic configuration:

```yaml
name: req
exec:
  script: main.py
requirements:
  - requirements.txt
include:
  - main.py
#   - requirements.txt
```

To me, requirements are "owned" by pyempaq as it installs them in a transparent way for users.

My PR ensures the requirements are always included whatever the user's configuration, as otherwise they can shoot themselves in the foot.

I've added tests in `test_integration.py` as there is already the tooling available to test the pack, not sure it is okay for you.

I haven't added a note in the docs as, to me, the correct behavior is described.

Let me know if the approach I've taken seems good to you !

### CODE REVIEW

**Comment by facundobatista** [comment]
Hello @ainquel !

I understand the problem, thanks for spotting it out.

I don't think we should copy files specifically excluded by the user though. That's a slippery slope and while I don't see a problem in *this* case, the future may prove different, so I'd like to enforce a rule like "if you use include/exclude options you have full power on what's copied and PyEmpaq will not contradict that behind your back".

So, with that in consideration, what's the best we can do? Of course we need to detect the problem at "pack time" and never crash when unpacking.

Maybe this is the best approach: detect that "the configuration is invalid" and alert the user. 

We can do that by instead of copying the requirement files, just asserting that they are included in the destination directory. Something like:

```
    # ensure requirements are always included
    for path in config.requirements:
        if not (origdir / path).exists():
            raise PackError(f"The indicated requirement {path!r} is not included along the packed files; please check the config.")
```

For better presentation of this (and other errors) I would do the following at the end of `main.py`... instead of just calling `pack(config)`:

```
try:
    pack(config)
except PackError as exc:
    logger.error("Pack error: %s", exc)
    exit(2)
except Exception as exc:
    logger.error("Unknown internal error: %r", exc)
    exit(3)
```

What do you think?

Thanks!!

**Comment by facundobatista** [comment]
Hello @ainquel:

Sorry for taking so long to answer. I've been thinking about this.

If I understand correctly your proposal is something like the following? Let's suppose the user has a project like...

```
README.md
script.py
requirements.txt
```

...and then in the config it includes the `README.md` and `script.py`, leaves out `requirements.txt` but declares it as a requirements file (so it's needed).

You say that instead of forcefully including it (your original proposal) or exiting with error because of "broken config" (my proposal) we should pack what the user says but keep the requirements file, finally having something like the following when unpacked:

```
- orig
  |-- README.md
  \-- script.py
- metadata.json
- venv
- requirements.txt
```

Where the `requirements.txt` in the last line there is the original one, so it's both "not included in the final files" and "be used to install dependencies". 

Right?

The problem is that the user may have several requirements.txt, and those files may be in several directories, and even the can be referenced from one to another. 

Something like...

```
(...)
- requirements1.txt
- foo
  |-- (...)
  \-- requirements2.txt
- bar
  |-- (...)
  \-- requirements3.txt
```
... where the file 1 and 2 have just dependencies, but file 3 has dependencies but also a `-r ../foo/requirements2.txt` line.

We *could* start reproducing the original project structure in the final unpacked directory so the relative references hold, but I think this could be very complex, and may escalate quickly (think about having (sym)linked files as part of this structure and needing to be right across platforms, etc).

Is it possible? Probably yes. Does it worth it? Don't know. Maybe in the future we can implement something like this if we have very good reasons, but for now I think that "forcing the user to include the referenced requirements files" is good enough.

I also thought about grabbing *the content* of the referenced files, store that in the metadata, and save them back to files when creating the virtualenv in destination, but this solution suffers from the same problem indicated above.

What do you think? Thanks!

**Comment by ainquel** [comment]
Hello,

> Sorry for taking so long to answer. I've been thinking about this.

No problem.

That's mostly it, if the user includes the whole directory, `README.md`, `script.py` and `requirements.txt` are copied in `orig` (users might want to parse it in their code for example) but we make sure requirements files are included in the archive, for example in a `requirements` folder. Each file can be named from its path something like what is done below (if we would want the exact path, for example, to show the problematic file in an error, a mapping could be added in the metadata).

```
- orig
  |-- README.md
  |-- requirements1.txt
  |-- script.py
  |-- foo/
    |-- requirements2.txt
- metadata.json
- venv
- requirements/
-  |-- requirements1.txt
-  \-- foo-requirements2.txt
```

But I didn't have in mind that a user can put a reference to another requirements into another one. So I agree with your conclusion that this proposal is not worth the complexity as it would have to handle recursive dependencies.
Thank you for giving it a thought.

So I'll see what I can do with your solution: "explicit check of requirements at pack time", it seems to be the better solution to avoid surprises for users and to maintain.

**Comment by facundobatista** [comment]
Wonderful, so let's go with the explicit check at pack time, thanks!!!

**Comment by ainquel** [comment]
So I've added:
- the check we've talked about
- a test to ensure pack is exiting when a requirement is missing
- a test to ensure a pack runs correctly when using requirements, with the default include (everything is included) and the explicit include (script and requirements included)

Let me know if it's okay for  you !

**Review by facundobatista — APPROVED** [review]
Wonderful, thanks!!

**Comment by facundobatista** [comment]
Thanks @ainquel for all the work!

**Pull request merged**
